# Generated by Django 3.1.12 on 2026-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20260510_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
    ]
