# Generated by Django 3.1.12 on 2026-05-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20260510_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tareaId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='usuarioId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
