# Generated by Django 3.1.12 on 2026-05-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20260511_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='usuarioId',
        ),
        migrations.AddField(
            model_name='agenda',
            name='usuarioCorreo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
