# Generated by Django 3.1.12 on 2026-05-21 18:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estadoTarea', models.CharField(choices=[('pendiente', 'Pendiente'), ('enProceso', 'En Proceso'), ('entregada', 'Entregada'), ('revisada', 'Revisada'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('usuarioCorreo', models.CharField(max_length=200)),
                ('estudianteCorreo', models.CharField(blank=True, default='', max_length=200)),
                ('adjuntos', djongo.models.fields.JSONField(blank=True, default=list)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=300)),
                ('usuarioCorreo', models.CharField(max_length=200)),
                ('usuarioNombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorCorreo', models.CharField(max_length=200)),
                ('autorNombre', models.CharField(max_length=200)),
                ('autorRol', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tareas.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('observaciones', models.TextField(blank=True, default='')),
                ('profesorCorreo', models.CharField(max_length=200)),
                ('profesorNombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='tareas.tarea')),
            ],
        ),
    ]
