# Generated by Django 3.1.12 on 2026-05-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_creacion',
            new_name='fechaCreacion',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_entrega',
            new_name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estadoTarea',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enProceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuarioResponsableId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
    ]
