# Generated by Django 3.1.12 on 2026-05-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20260510_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuarioResponsableId',
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuarioCorreo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
