# Generated by Django 3.1.12 on 2026-05-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCorreo', models.CharField(max_length=200)),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True)),
                ('tipoReporte', models.CharField(default='mensual', max_length=20)),
                ('totalTareas', models.IntegerField(default=0)),
                ('tareasPendientes', models.IntegerField(default=0)),
                ('tareasEnProceso', models.IntegerField(default=0)),
                ('tareasCompletadas', models.IntegerField(default=0)),
                ('totalAgendas', models.IntegerField(default=0)),
                ('agendasPendientes', models.IntegerField(default=0)),
                ('agendasCompletadas', models.IntegerField(default=0)),
                ('agendasCanceladas', models.IntegerField(default=0)),
                ('agendasAltaPrioridad', models.IntegerField(default=0)),
                ('tareasAgendadas', models.IntegerField(default=0)),
                ('tareasSinAgendar', models.IntegerField(default=0)),
                ('productividad', models.FloatField(default=0)),
            ],
        ),
    ]
