# Generated by Django 3.1.12 on 2026-05-09 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporteId', models.CharField(max_length=20, unique=True, verbose_name='ID del reporte')),
                ('nombreReporte', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fechaGeneracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('totalUsuarios', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total usuarios')),
                ('totalTareas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total tareas')),
                ('tareasCompletadas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tareas completadas')),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Eficiencia (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Reporte activo')),
                ('metricas', models.JSONField(blank=True, default=dict, verbose_name='Métricas adicionales')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-fechaGeneracion'],
            },
        ),
    ]
