# Generated by Django 3.1.12 on 2026-05-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='metricas',
        ),
    ]
